In [ ]:
import sqlite3

conn = sqlite3.connect("train_delay.db")

In [ ]:
import pandas as pd

df = pd.read_excel("/content/Indian_Train_Delay_Cleaned.xlsx")

df.head()

,train_number,train_name,station_code,station_name,average_delay_minutes,pct_right_time,pct_slight_delay,pct_significant_delay,pct_cancelled_unknown,scraped_at,source_url
0,12673,Cheran Express,MAS,CHENNAI CENTRAL,2.0,98.90,0.27,0.00,0.83,2025-09-27T12:25:37.767628+00:00,https://etrain.info/train/Cheran-Express-12673...
1,12673,Cheran Express,AVD,AVADI,0.0,0.27,0.00,0.00,99.73,2025-09-27T12:25:39.293769+00:00,https://etrain.info/train/Cheran-Express-12673...
2,12673,Cheran Express,AJJ,ARAKKONAM,16.0,55.34,44.38,0.27,0.01,2025-09-27T12:25:40.672610+00:00,https://etrain.info/train/Cheran-Express-12673...
3,12673,Cheran Express,KPD,KATPADI JN,17.0,48.49,49.86,1.64,0.01,2025-09-27T12:25:42.125216+00:00,https://etrain.info/train/Cheran-Express-12673...
4,12673,Cheran Express,JTJ,JOLARPETTAI,NaN,70.96,27.67,1.37,0.00,2025-09-27T12:25:44.585700+00:00,https://etrain.info/train/Cheran-Express-12673...

In [ ]:
import sqlite3

conn = sqlite3.connect("train_delay.db")

In [ ]:
df.to_sql(
    "train_delays",
    conn,
    if_exists="replace",
    index=False
)

1900

In [ ]:
query = """
SELECT *
FROM train_delays
LIMIT 5;
"""

pd.read_sql_query(query, conn)

,train_number,train_name,station_code,station_name,average_delay_minutes,pct_right_time,pct_slight_delay,pct_significant_delay,pct_cancelled_unknown,scraped_at,source_url
0,12673,Cheran Express,MAS,CHENNAI CENTRAL,2.0,98.90,0.27,0.00,0.83,2025-09-27T12:25:37.767628+00:00,https://etrain.info/train/Cheran-Express-12673...
1,12673,Cheran Express,AVD,AVADI,0.0,0.27,0.00,0.00,99.73,2025-09-27T12:25:39.293769+00:00,https://etrain.info/train/Cheran-Express-12673...
2,12673,Cheran Express,AJJ,ARAKKONAM,16.0,55.34,44.38,0.27,0.01,2025-09-27T12:25:40.672610+00:00,https://etrain.info/train/Cheran-Express-12673...
3,12673,Cheran Express,KPD,KATPADI JN,17.0,48.49,49.86,1.64,0.01,2025-09-27T12:25:42.125216+00:00,https://etrain.info/train/Cheran-Express-12673...
4,12673,Cheran Express,JTJ,JOLARPETTAI,NaN,70.96,27.67,1.37,0.00,2025-09-27T12:25:44.585700+00:00,https://etrain.info/train/Cheran-Express-12673...

In [ ]:
query = """
SELECT
    train_number,
    train_name,
    ROUND(AVG(average_delay_minutes), 2) AS avg_delay_minutes
FROM train_delays
GROUP BY train_number, train_name
ORDER BY avg_delay_minutes DESC
LIMIT 10;
"""

pd.read_sql_query(query, conn)

   train_number            train_name  avg_delay_minutes
0         12261        Howrah Duronto             370.50
1         12262        Howrah Duronto             316.83
2         12236       Duronto Express             148.00
3         12509  Guwahati Sbc Express             143.19
4         12839           Howrah Mail             109.37
5         12626        Kerala Express             101.05
6         12840           Howrah Mail             100.81
7         12510  Sbc Guwahati Express              87.97
8         12245       Duronto Express              78.20
9         12842    Coromandel Express              65.53

In [ ]:
query = """
SELECT
    train_number,
    train_name,
    ROUND(AVG(pct_right_time), 2) AS avg_right_time_pct
FROM train_delays
GROUP BY train_number, train_name
HAVING AVG(pct_right_time) > 90
ORDER BY avg_right_time_pct DESC;
"""

pd.read_sql_query(query, conn)

   train_number               train_name  avg_right_time_pct
0         12306         Kolkata Rajdhani              100.00
1         12049         Gatimaan Express               97.12
2         12957  Swarna Jayanti Rajdhani               96.34
3         12680     Coimbatore Intercity               93.33

In [ ]:
query = """
SELECT
    station_code,
    station_name,
    ROUND(AVG(average_delay_minutes), 2) AS avg_delay_minutes,
    COUNT(*) AS record_count
FROM train_delays
GROUP BY station_code, station_name
HAVING COUNT(*) >= 10
ORDER BY avg_delay_minutes DESC
LIMIT 10;
"""

pd.read_sql_query(query, conn)

  station_code           station_name  avg_delay_minutes  record_count
0          BBS            BHUBANESWAR              94.50            10
1          HWH              HOWRAH JN              77.67            20
2         CSMT  C SHIVAJI TERM MUMBAI              75.18            12
3          KYN              KALYAN JN              70.24            18
4          NGP                 NAGPUR              66.67            10
5          BZA          VIJAYAWADA JN              57.44            18
6          PER               PERAMBUR              44.44            10
7          AJJ              ARAKKONAM              34.50            16
8          KPD             KATPADI JN              31.71            18
9           ED               ERODE JN              30.89            10

In [ ]:
query = """
SELECT
    station_code,
    station_name,
    ROUND(AVG(pct_right_time), 2) AS avg_right_time_pct,
    COUNT(*) AS record_count
FROM train_delays
GROUP BY station_code, station_name
HAVING COUNT(*) >= 10
ORDER BY avg_right_time_pct DESC
LIMIT 10;
"""

pd.read_sql_query(query, conn)

  station_code               station_name  avg_right_time_pct  record_count
0          CBE              COIMBATORE JN               87.34            10
1           ST                      SURAT               85.37            10
2          MAS            CHENNAI CENTRAL               84.57            22
3          BRC                VADODARA JN               84.31            10
4         NDLS                  NEW DELHI               81.79            24
5          MDU                 MADURAI JN               80.90            10
6          NZM               H NIZAMUDDIN               79.88            14
7          DDU  PT DEEN DAYAL UPADHYAY JN               79.52            16
8         CSMT      C SHIVAJI TERM MUMBAI               76.27            12
9         VGLJ        V LAKSHMIBAI JHANSI               75.76            14

In [ ]:
query = """
SELECT
    train_number,
    train_name,
    average_delay_minutes,
    CASE
        WHEN average_delay_minutes IS NULL THEN 'No Data'
        WHEN average_delay_minutes = 0 THEN 'On Time'
        WHEN average_delay_minutes <= 15 THEN 'Slight Delay'
        WHEN average_delay_minutes <= 60 THEN 'Moderate Delay'
        ELSE 'High Delay'
    END AS delay_category
FROM train_delays
LIMIT 20;
"""

pd.read_sql_query(query, conn)

    train_number      train_name  average_delay_minutes  delay_category
0          12673  Cheran Express                    2.0    Slight Delay
1          12673  Cheran Express                    0.0         On Time
2          12673  Cheran Express                   16.0  Moderate Delay
3          12673  Cheran Express                   17.0  Moderate Delay
4          12673  Cheran Express                    NaN         No Data
5          12673  Cheran Express                   25.0  Moderate Delay
6          12673  Cheran Express                   25.0  Moderate Delay
7          12673  Cheran Express                   24.0  Moderate Delay
8          12673  Cheran Express                   13.0    Slight Delay
9          12673  Cheran Express                    NaN         No Data
10         12674  Cheran Express                    5.0    Slight Delay
11         12674  Cheran Express                    NaN         No Data
12         12674  Cheran Express                   21.0  Moderate Delay
13         12674  Cheran Express                   24.0  Moderate Delay
14         12674  Cheran Express                    7.0    Slight Delay
15         12674  Cheran Express                   14.0    Slight Delay
16         12674  Cheran Express                   28.0  Moderate Delay
17         12674  Cheran Express                   32.0  Moderate Delay
18         12674  Cheran Express                    NaN         No Data
19         12681   Kovai Express                    4.0    Slight Delay

In [ ]:
query = """
SELECT
    CASE
        WHEN average_delay_minutes IS NULL THEN 'No Data'
        WHEN average_delay_minutes = 0 THEN 'On Time'
        WHEN average_delay_minutes <= 15 THEN 'Slight Delay'
        WHEN average_delay_minutes <= 60 THEN 'Moderate Delay'
        ELSE 'High Delay'
    END AS delay_category,
    COUNT(*) AS record_count
FROM train_delays
GROUP BY delay_category
ORDER BY record_count DESC;
"""

pd.read_sql_query(query, conn)

   delay_category  record_count
0  Moderate Delay           841
1    Slight Delay           491
2      High Delay           314
3         No Data           236
4         On Time            18

In [ ]:
query = """
SELECT
    train_number,
    train_name,
    ROUND(AVG(average_delay_minutes), 2) AS avg_delay_minutes,
    RANK() OVER (
        ORDER BY AVG(average_delay_minutes) DESC
    ) AS delay_rank
FROM train_delays
GROUP BY train_number, train_name;
"""

pd.read_sql_query(query, conn)

    train_number            train_name  avg_delay_minutes  delay_rank
0          12261        Howrah Duronto             370.50           1
1          12262        Howrah Duronto             316.83           2
2          12236       Duronto Express             148.00           3
3          12509  Guwahati Sbc Express             143.19           4
4          12839           Howrah Mail             109.37           5
..           ...                   ...                ...         ...
85         12434              Rajdhani               6.75          86
86         12010              Shatabdi               6.43          87
87         12680  Coimbatore Intercity               5.31          88
88         12306      Kolkata Rajdhani               1.63          89
89         12049      Gatimaan Express               1.50          90

[90 rows x 4 columns]

In [ ]:
query = """
SELECT *
FROM (
    SELECT
        train_number,
        train_name,
        ROUND(AVG(average_delay_minutes), 2) AS avg_delay_minutes,
        RANK() OVER (
            ORDER BY AVG(average_delay_minutes) DESC
        ) AS delay_rank
    FROM train_delays
    GROUP BY train_number, train_name
)
WHERE delay_rank <= 5;
"""

pd.read_sql_query(query, conn)

   train_number            train_name  avg_delay_minutes  delay_rank
0         12261        Howrah Duronto             370.50           1
1         12262        Howrah Duronto             316.83           2
2         12236       Duronto Express             148.00           3
3         12509  Guwahati Sbc Express             143.19           4
4         12839           Howrah Mail             109.37           5

In [ ]:
query = """
SELECT
    COUNT(*) AS total_records,
    COUNT(DISTINCT train_number) AS unique_trains,
    COUNT(DISTINCT station_code) AS unique_stations,
    ROUND(AVG(average_delay_minutes), 2) AS avg_delay_minutes,
    ROUND(AVG(pct_right_time), 2) AS avg_right_time_pct,
    ROUND(AVG(pct_slight_delay), 2) AS avg_slight_delay_pct,
    ROUND(AVG(pct_significant_delay), 2) AS avg_significant_delay_pct,
    ROUND(AVG(pct_cancelled_unknown), 2) AS avg_cancelled_unknown_pct
FROM train_delays;
"""

pd.read_sql_query(query, conn)

,total_records,unique_trains,unique_stations,avg_delay_minutes,avg_right_time_pct,avg_slight_delay_pct,avg_significant_delay_pct,avg_cancelled_unknown_pct
0,1900,90,480,40.7,50.41,32.97,15.45,1.17

In [ ]:
query = """
SELECT
    ROUND(MAX(average_delay_minutes), 2) AS maximum_delay,
    ROUND(MIN(average_delay_minutes), 2) AS minimum_delay
FROM train_delays;
"""

pd.read_sql_query(query, conn)

   maximum_delay  minimum_delay
0          586.0            0.0